09/20/2013 10:24:45.918 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 487, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 65, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 367, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 162, in battle_system
    candy_system(room)
TypeError: candy_system() takes exactly 2 arguments (1 given)

09/20/2013 10:56:56.3 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 505, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 65, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 385, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 182, in battle_system
    gold = room.monster[0].attrs['gold']
KeyError: 'gold'

09/20/2013 10:57:00.308 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 446, in <module>
    if room.room_name[0].value in ['Potos Inn', 'Pandora Inn', 'Dwarf Village Inn', 'Kakkara Inn', 'Mandala Inn','Gold Island Inn']:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 63, in main
    verb, noun = parse_command(command)
EOFError: EOF when reading a line

09/20/2013 10:57:00.500 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 487, in <module>
    for monster in room.monster:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 10:57:00.666 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 495, in <module>
    for room_exit in room.exit:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 10:57:00.822 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 508, in <module>
    logger.write_line([exception_string])
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 65, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 454, in run_command
    elif verb == "stats" or verb == "Stats":
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 351, in store_system
    player_inventory.append('Candy')
EOFError: EOF when reading a line

09/20/2013 11:20:20.742 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 505, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 55, in main
    starting_room = int(player.attrs["room"])
ValueError: invalid literal for int() with base 10: 'Mana Fortress Final Area'

09/20/2013 11:36:23.876 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 513, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 12:18:20.66 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 513, in <module>
    exception_string = traceback.format_exc()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 12:18:20.199 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 511, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 12:45:50.972 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 511, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 29, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/20/2013 12:53:29.135 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 511, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 13:49:28.547 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 519, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 49, in main
    for room in game_map.building:
AttributeError: 'tuple' object has no attribute 'building'

09/20/2013 13:52:16.755 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 519, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 66, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 400, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 187, in battle_system
    score_system(room, score)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 256, in score_system
    score = score + enemy_score
TypeError: unsupported operand type(s) for +: 'int' and 'unicode'

09/20/2013 14:12:22.677 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 519, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 66, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 400, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 136, in battle_system
    score = int(room.monster[0].attrs['score'])
KeyError: 'score'

09/20/2013 15:00:02.234 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 519, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 63, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 15:14:15.52 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 527, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 15:20:35.965 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 535, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 15:20:38.36 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 527, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 15:47:23.522 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 541, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 65, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/20/2013 15:51:55.479 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 545, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 426, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 171, in battle_system
    print 'Player Health:', character['player_stats']['health']
NameError: global name 'character' is not defined

09/20/2013 15:53:52.716 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 545, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 426, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 171, in battle_system
    print 'Player Health:', character['player_stats']['health']
NameError: global name 'character' is not defined

09/20/2013 15:56:37.529 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 427, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 165, in battle_system
    for character in player:
TypeError: 'player_q2class' object is not iterable

09/20/2013 16:11:19.729 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 545, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 426, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 207, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 410, in end_the_game
    if room.monster[0].endcode[0] == '1':
AttributeError: 'monster_q2class' object has no attribute 'endcode'

09/20/2013 16:13:46.223 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 545, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 426, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 207, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 410, in end_the_game
    if room.monster[0].attrs['endcode'] == '1':
KeyError: 'endcode'

09/20/2013 16:18:15.619 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 427, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 207, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 410, in end_the_game
    if room.monster[0].attrs['endcode']:
KeyError: 'endcode'

09/20/2013 16:45:43.214 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

