09/23/2013 09:52:50.66 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 549, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 59, in main
    print room.player[0].attrs['name']
AttributeError: 'building_q2class' object has no attribute 'player'

09/23/2013 09:54:18.554 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 558, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 421, in run_command
    print room.player[0].attrs['name']
AttributeError: 'building_q2class' object has no attribute 'player'

09/23/2013 09:55:25.792 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 554, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 421, in run_command
    print map.player[0].attrs['name']
AttributeError: 'builtin_function_or_method' object has no attribute 'player'

09/23/2013 09:59:20.566 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 554, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 72, in main
    pygame.mixer.init()
EOFError: EOF when reading a line

09/23/2013 09:59:21.202 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 555, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:04:29.848 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 557, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 65, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:09:29.560 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 559, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 54, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 131, in party_builder
    party = {Randi, Purim, Popoie}
TypeError: unhashable type: 'dict'

09/23/2013 10:11:13.47 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 54, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 128, in party_builder
    Randi = {'Player Level': game_map.player.attrs['Level'], 'Player Exp': 0, 'Next Level': 25, 'player_stats' : {'Strength': 1, 'Dexterity': 1, 'Endurance': 1, 'attack' :[5, 12], 'health': 100}}
AttributeError: 'list' object has no attribute 'attrs'

09/23/2013 10:11:27.687 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 54, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 128, in party_builder
    Randi = {'Player Level': game_map.player.attrs['level'], 'Player Exp': 0, 'Next Level': 25, 'player_stats' : {'Strength': 1, 'Dexterity': 1, 'Endurance': 1, 'attack' :[5, 12], 'health': 100}}
AttributeError: 'list' object has no attribute 'attrs'

09/23/2013 10:15:31.116 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 54, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 132, in party_builder
    print Randi[0]
KeyError: 0

09/23/2013 10:15:44.361 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 560, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 65, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:15:44.488 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 65, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:15:44.611 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 65, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:15:44.739 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 30, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/23/2013 10:41:00.342 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 561, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 65, in main
    last_room = current_room
EOFError: EOF when reading a line

09/23/2013 10:41:00.715 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 66, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:41:01.59 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 66, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:41:01.594 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 66, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:41:02.451 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 569, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 66, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 10:45:08.480 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 236, in experience_system
    character["Player Exp"]+= gained_exp
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 10:50:56.974 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 236, in experience_system
    character[int("playerxp")]+= gained_exp
ValueError: invalid literal for int() with base 10: 'playerxp'

09/23/2013 10:52:53.988 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 236, in experience_system
    character["playerxp"] += gained_exp
KeyError: 'playerxp'

09/23/2013 10:54:08.276 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 236, in experience_system
    character["Player Exp"]+= gained_exp
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 10:56:03.171 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 236, in experience_system
    character["Player Exp"]+= int(gained_exp)
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 11:00:38.152 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 236, in experience_system
    character[int("Player Exp")]+= int(gained_exp)
ValueError: invalid literal for int() with base 10: 'Player Exp'

09/23/2013 11:10:37.483 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 446, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 237, in experience_system
    character["Player Exp"]+= gained_exp
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 11:12:47.866 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 69, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 218, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in experience_system
    character["Player Exp"]+= gained_exp
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 11:14:00.594 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 569, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 449, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 240, in experience_system
    character["Player Exp"]+= gained_exp
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 11:26:29.168 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 56, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 134, in party_builder
    Randi = {'Name': game_map.player[0].attrs['name'], 'Player Level': int(game_map.player[0].attrs['level']), 'Player Exp': int(game_map.player[0].attrs['playerxp']), 'Next Level': int(game_map.player[0].attrs['Nextlvl']), 'player_stats' : {'Strength': int(game_map.player[0].attrs['strength']), 'Dexterity': int(game_map.player[0].attrs['dexterity']), 'Endurance': int(game_map.player[0].attrs['endurance']), 'attack' :int([game_map.player[0].attrs['attack1'], game_map.player[0].attrs['attack2']]), 'health': 100}}
TypeError: int() argument must be a string or a number, not 'list'

09/23/2013 11:27:27.850 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 56, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 134, in party_builder
    Randi = {'Name': game_map.player[0].attrs['name'], 'Player Level': literal_eval(game_map.player[0].attrs['level']), 'Player Exp': literal_eval(game_map.player[0].attrs['playerxp']), 'Next Level': literal_eval(game_map.player[0].attrs['Nextlvl']), 'player_stats' : {'Strength': literal_eval(game_map.player[0].attrs['strength']), 'Dexterity': literal_eval(game_map.player[0].attrs['dexterity']), 'Endurance': literal_eval(game_map.player[0].attrs['endurance']), 'attack' :literal_eval([game_map.player[0].attrs['attack1'], game_map.player[0].attrs['attack2']]), 'health': 100}}
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 11:28:18.658 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 239, in experience_system
    character["Player Exp"]+= gained_exp
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 11:36:06.63 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 446, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 239, in experience_system
    while characters['Player Exp'] >= literal_eval(characters)['Next Level']:
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 11:36:58.773 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 241, in experience_system
    characters["Player Level"] += 1
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 11:39:09.756 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 11:39:10.341 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 11:39:10.512 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 11:39:10.661 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 11:39:11.444 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    if __name__ =="__main__":
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 11:39:13.279 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:01:04.128 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 242, in experience_system
    characters["Player Level"] += 1
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 12:03:39.82 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:03:39.280 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    except:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:03:39.465 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:05:10.223 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in experience_system
    characters["Player Exp"] = literal_eval(characters["Player Exp"])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:07:03.742 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in experience_system
    characters["Player Exp"] = literal_eval(characters["Player Exp"]) + 0
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:07:43.952 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 248, in experience_system
    characters['player_stats']['Strength'] += nstr
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 12:10:25.308 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = (characters['player_stats']['attack'][0] + (characters['player_stats']['Strength']), (characters['player_stats']['attack'][1] + characters['player_stats']['Strength'] * 2))
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 12:11:57.365 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval((characters['player_stats']['attack'][0]) + literal_eval((characters['player_stats']['Strength'])), literal_eval((characters['player_stats']['attack'][1]) + literal_eval(characters['player_stats']['Strength'] * 2)))
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:16:35.666 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack1'] = literal_eval((characters['player_stats']['attack'][0]) + literal_eval((characters['player_stats']['Strength'])))
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:18:24. Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack1'] = literal_eval((characters['player_stats']['attack1'][0]) + literal_eval((characters['player_stats']['Strength'])))
KeyError: 'attack1'

09/23/2013 12:20:01.447 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval((characters['player_stats']['attack1'][0]) + literal_eval((characters['player_stats']['Strength']))), literal_eval((characters['player_stats']['attack2'][1]) + literal_eval(characters['player_stats']['Strength'] * 2))
KeyError: 'attack1'

09/23/2013 12:20:53.535 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval((characters['player_stats']['attack'][0]) + literal_eval((characters['player_stats']['Strength']))), literal_eval((characters['player_stats']['attack'][1]) + literal_eval(characters['player_stats']['Strength'] * 2))
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:21:37.511 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:22:59.509 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:24:43.453 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:27:34.411 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:28:53.651 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:34:29.136 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 446, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 253, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:35:05.712 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 446, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 239, in experience_system
    characters['attack'] = literal_eval([int(game_map.player[0].attrs['attack1']), int(game_map.player[0].attrs['attack2'])])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:38:15.143 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 564, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 444, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 251, in experience_system
    characters['player_stats']['attack'] = literal_eval(characters['player_stats']['attack'])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 12:40:24.352 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:40:24.488 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 564, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:40:24.623 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 564, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 12:42:37.252 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 564, in <module>
    except:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 13:27:38.371 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 237, in experience_system
    characters["Player Exp"] = literal_eval(characters["Player Exp"]) + gained_exp
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 13:28:44.419 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 237, in experience_system
    characters["Player Exp"] = literal_eval(characters["Player Exp"]) + gained_exp
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 13:29:54.795 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 219, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in experience_system
    characters["Next Level"] = literal_eval(characters["Next Level"])
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/23/2013 13:30:51.314 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 32, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/23/2013 13:30:51.803 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 13:31:39.940 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 13:33:15.977 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 13:40:34.477 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 187, in battle_system
    monster_health = damage(character, int(monster_health))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 316, in damage
    attacker['player_stats']['attack'][0] = int(attacker['player_stats']['attack'][0])
TypeError: 'tuple' object does not support item assignment

09/23/2013 13:41:26.857 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 178, in battle_system
    character["player_stats"]['attack'] = (character["player_stats"]['attack'][0] + 12) , (character["player_stats"]['attack'][1] + 18)
IndexError: list index out of range

09/23/2013 13:49:14.481 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 189, in battle_system
    monster_health = damage(characters, int(monster_health))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 318, in damage
    attacker['player_stats']['attack'][0] = int(attacker['player_stats']['attack'][0])
TypeError: 'unicode' object does not support item assignment

09/23/2013 13:52:14.519 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 189, in battle_system
    monster_health = damage(characters, int(monster_health))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 323, in damage
    damage = random.randint(attacker['player_stats']['attack'][0], attacker['player_stats']['attack'][1]) * 1.1
TypeError: 'int' object has no attribute '__getitem__'

09/23/2013 13:53:02.398 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 192, in battle_system
    dodge_chance = random.randint( 0, (100 / characters['player_stats']['Dexterity']))
TypeError: unsupported operand type(s) for /: 'int' and 'unicode'

09/23/2013 13:56:44.813 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 188, in battle_system
    print character['name']
KeyError: 'name'

09/23/2013 13:56:58.983 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 13:58:06. Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 447, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 186, in battle_system
    print character['Name'], 'is up to fight'
EOFError: EOF when reading a line

09/23/2013 13:58:28.747 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 186, in battle_system
    print character['Name'], 'is up to fight'
KeyError: 'Name'

09/23/2013 13:59:49.67 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:01:01.532 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 568, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 448, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 187, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:02:05.303 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 569, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 449, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 187, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:03:13.721 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 572, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 452, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 187, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:03:59.667 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 451, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 179, in battle_system
    characters["player_stats"]['attack'] = characters["player_stats"]['attack'][1] + 18
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 14:05:50.917 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 451, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 179, in battle_system
    characters["player_stats"]['attack'] = characters["player_stats"]['attack'] + 18
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 14:06:58.995 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 573, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 453, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 188, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:07:40.487 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 574, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 454, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 188, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:09:02.136 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 574, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 454, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 188, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:10:08.343 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 576, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 456, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 188, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:10:34.763 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 56, in main
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 134, in party_builder
    Randi = {'Name': game_map.player[0].attrs['name'], 'Player Level': game_map.player[0].attrs['level'], 'Player Exp': game_map.player[0].attrs['playerxp'], 'Next Level': game_map.player[0].attrs['Nextlvl'], 'player_stats' : {'Strength': game_map.player[0].attrs['strength'], 'Dexterity': game_map.player[0].attrs['dexterity'], 'Endurance': game_map.player[0].attrs['endurance'], 'attack' :game_map.player[0].attrs['attack1'], 'health': 100}}
KeyError: 'name'

09/23/2013 14:11:15.177 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:11:46.693 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 546, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:13:52.901 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 451, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 188, in battle_system
    print characters['attack']
KeyError: 'attack'

09/23/2013 14:19:06.700 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 451, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 189, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:19:07.49 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 571, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 451, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 189, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 14:24:40.817 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 562, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 442, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 177, in battle_system
    character["player_stats"]['attack'] = (character["player_stats"]['attack'][0] + 12) , (character["player_stats"]['attack'][1] + 18)
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 14:25:28.936 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 562, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 442, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 177, in battle_system
    character["player_stats"]['attack'] = (character["player_stats"]['attack'] + 18)
TypeError: coercing to Unicode: need string or buffer, int found

09/23/2013 14:26:12.756 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 170, in battle_system
    character["player_stats"]['attack'] = int(character["player_stats"]['attack'])
NameError: global name 'character' is not defined

09/23/2013 14:28:12.526 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:29:01.898 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 443, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 182, in battle_system
    print character['name'], character['player_stats']['health']
KeyError: 'name'

09/23/2013 14:31:42.854 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 563, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:33:44.368 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 565, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 445, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 192, in battle_system
    dodge_chance = random.randint( 0, (100 / character['player_stats']['Dexterity']))
TypeError: unsupported operand type(s) for /: 'int' and 'unicode'

09/23/2013 14:33:51.733 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 564, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 444, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 185, in battle_system
    print character['Name'] , 'is up to fight'
EOFError: EOF when reading a line

09/23/2013 14:34:40.956 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 566, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:36:07.916 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:38:06.392 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:57:57.340 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 14:58:31.60 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 567, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:00:14.887 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 564, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:04:35.515 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 569, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:05:48.642 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 581, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 461, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 170, in battle_system
    character1 = character[0]
KeyError: 0

09/23/2013 15:06:22.998 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 581, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 32, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/23/2013 15:08:55.46 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 581, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 70, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 461, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 197, in battle_system
    if dodge_chance == 25:
UnboundLocalError: local variable 'dodge_chance' referenced before assignment

09/23/2013 15:10:27.622 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 581, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:21:50.525 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 592, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 470, in run_command
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 134, in party_builder
    if room.party.attrs['member'] == '0':
AttributeError: 'list' object has no attribute 'attrs'

09/23/2013 15:23:17.522 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 592, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 470, in run_command
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 134, in party_builder
    if room.party.attrs['member'] == '0':
AttributeError: 'list' object has no attribute 'attrs'

09/23/2013 15:24:42.436 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 592, in <module>
    for room_exit in room.exit:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:25:06.853 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 598, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 547, in run_command
    print character
NameError: global name 'character' is not defined

09/23/2013 15:26:50.776 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 607, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 485, in run_command
    party_builder(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 150, in party_builder
    if room.party[0].attrs['member'] == '2':
IndexError: list index out of range

09/23/2013 15:28:17.253 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 609, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 489, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 197, in battle_system
    character2 = party[1]
IndexError: list index out of range

09/23/2013 15:33:10.561 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 611, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 491, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 234, in battle_system
    character2['player_stats']['health'] = character2['player_stats']['health'] - monster_damage
UnboundLocalError: local variable 'character2' referenced before assignment

09/23/2013 15:36:28.298 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 623, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:38:38.501 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 623, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 503, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 215, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/23/2013 15:39:12.796 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 623, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:40:07.385 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 623, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 15:45:58.731 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 623, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 503, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in battle_system
    character2['player_stats']['health'] = character2['player_stats']['health'] - monster_damage
UnboundLocalError: local variable 'character2' referenced before assignment

09/23/2013 15:48:53.506 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 623, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 503, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 235, in battle_system
    character1['player_stats']['health'] = character1['player_stats']['health'] - monster_damage
UnboundLocalError: local variable 'character1' referenced before assignment

09/23/2013 15:56:13.717 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 626, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 502, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 235, in battle_system
    character1['player_stats']['health'] = character1['player_stats']['health'] - monster_damage
UnboundLocalError: local variable 'character1' referenced before assignment

09/23/2013 16:14:01.908 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 505, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in battle_system
    character1['player_stats']['health'] = character1['player_stats']['health'] - monster_damage
UnboundLocalError: local variable 'character1' referenced before assignment

09/23/2013 16:16:02.35 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 67, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 505, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 238, in battle_system
    character1['player_stats']['health'] = character1['player_stats']['health'] - monster_damage
UnboundLocalError: local variable 'character1' referenced before assignment

09/23/2013 16:17:10.435 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 16:19:26.9 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 16:28:23.31 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 16:32:03.281 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 16:33:14.974 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 16:55:17.944 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/23/2013 19:59:04.503 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 629, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/text_of_mana_party_test.py", line 64, in main
    command = raw_input(">")
EOFError: EOF when reading a line

