09/27/2013 09:34:47.445 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 814, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 589, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 297, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 808, in high_score
    sorted_by_second = sorted(fout, key=lambda tup: tup[1])
IOError: File not open for reading

09/27/2013 09:44:55.823 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 817, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 589, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 10:19:19.579 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 33, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 10:28:14.114 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 590, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 805, in high_score
    butts = literal_eval(item)
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/27/2013 10:29:28.352 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    os.system('CLS')
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 589, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    high_score()
EOFError: EOF when reading a line

09/27/2013 10:29:28.598 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 822, in <module>
    if __name__ =="__main__":
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    os.system('CLS')
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 589, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    high_score()
EOFError: EOF when reading a line

09/27/2013 10:29:28.718 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    os.system('CLS')
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 589, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    high_score()
EOFError: EOF when reading a line

09/27/2013 10:29:29.270 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 72, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/27/2013 10:30:17.438 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 590, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 810, in high_score
    butts = literal_eval(item)
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/27/2013 10:30:56.733 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 590, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 298, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 810, in high_score
    butts = literal_eval(str(item))
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/27/2013 10:40:14.737 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 76, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 591, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 299, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 809, in high_score
    board.append((player.get_points(), player_name.rstrip()))
AttributeError: 'player_q2class' object has no attribute 'get_points'

09/27/2013 10:42:19.83 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 76, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 591, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 299, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 812, in high_score
    with open("saves\\leaderboard.db", 'wb') as leaderboard_file:
IOError: [Errno 2] No such file or directory: 'saves\\leaderboard.db'

09/27/2013 10:42:24.610 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 816, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    os.system('CLS')
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 590, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 299, in battle_system
    high_score()
EOFError: EOF when reading a line

09/27/2013 10:42:24.971 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 816, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    os.system('CLS')
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 590, in run_command
    if monsters:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 299, in battle_system
    high_score()
EOFError: EOF when reading a line

09/27/2013 10:45:12.796 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 821, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 76, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 591, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 299, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 803, in high_score
    with open("high_score.db", 'rb') as high_scores:
IOError: [Errno 2] No such file or directory: 'high_score.db'

09/27/2013 10:49:46.704 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 300, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 809, in high_score
    score = literal_eval(line)
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/27/2013 10:50:39.998 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 300, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 809, in high_score
    score = literal_eval(line)
  File "C:\Python27\lib\ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "C:\Python27\lib\ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

09/27/2013 10:52:23.458 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 301, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 11:02:10.101 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    except SystemExit:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 301, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 11:02:10.517 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 819, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 301, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 11:03:07.842 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 300, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 805, in high_score
    fileOpen.append(player_name, score)
AttributeError: 'str' object has no attribute 'append'

09/27/2013 11:03:55.552 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 300, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 809, in high_score
    scores.append(player_name, score)
TypeError: append() takes exactly one argument (2 given)

09/27/2013 11:04:20.368 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 820, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 300, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 812, in high_score
    print name + ' ' * 5 + str(scores)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

09/27/2013 11:08:16.97 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 300, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 812, in high_score
    fout.write(scores)
TypeError: expected a character buffer object

09/27/2013 11:16:08.120 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 828, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 301, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 11:18:52.501 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 824, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 592, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 301, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 11:19:58.251 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 828, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 36, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 11:20:44.535 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 597, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 306, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/27/2013 11:40:09.769 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/27/2013 11:40:49.551 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/27/2013 11:43:36.490 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 597, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 305, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 818, in high_score
    score = literal_eval(line)
  File "C:\Python27\lib\ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Python27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
   ^
SyntaxError: unexpected EOF while parsing

09/27/2013 11:44:05.753 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 36, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 11:51:32.361 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/27/2013 11:53:51.742 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 829, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 597, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 319, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 565, in end_the_game
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 818, in high_score
    score = literal_eval(line)
  File "C:\Python27\lib\ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Python27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
   ^
SyntaxError: unexpected EOF while parsing

09/27/2013 14:32:36.946 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 827, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 36, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 14:58:33.776 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 847, in <module>
    print (name + ' ' * 5 + str(points)).center(50)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/27/2013 15:17:18.290 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 859, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 75, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/27/2013 15:45:18.750 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 858, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 37, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 16:26:16.963 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 859, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 38, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 16:28:59.564 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 859, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 38, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/27/2013 17:23:49.797 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 853, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 77, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 622, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 329, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

