09/19/2013 11:49:28.483 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 375, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 59, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 12:50:25.879 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 253, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 98, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/19/2013 13:11:20.996 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 60, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 256, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 129, in battle_system
    gold = room.monster.attrs['Gold']
AttributeError: 'list' object has no attribute 'attrs'

09/19/2013 13:12:41.592 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 60, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 256, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 129, in battle_system
    gold = room.monster[0].attrs['Gold']
KeyError: 'Gold'

09/19/2013 13:12:48.669 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 371, in <module>
    locked[room_exit.attrs["name"]] = room_exit.attrs["locked"]
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 59, in main
    os.system('CLS')
EOFError: EOF when reading a line

09/19/2013 13:12:48.798 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 371, in <module>
    locked[room_exit.attrs["name"]] = room_exit.attrs["locked"]
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 59, in main
    os.system('CLS')
EOFError: EOF when reading a line

09/19/2013 13:15:03.168 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 60, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 256, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 130, in battle_system
    wallet(int(gold))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 194, in wallet
    wallet = wallet + gold
TypeError: unsupported operand type(s) for +: 'function' and 'int'

09/19/2013 13:16:14.40 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 60, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 256, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 130, in battle_system
    wallet(gold)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 194, in wallet
    wallet = wallet + int(gold)
TypeError: unsupported operand type(s) for +: 'function' and 'int'

09/19/2013 13:18:41.505 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 60, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 256, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 130, in battle_system
    wallet(gold)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 194, in wallet
    wallet = int(wallet) + int(gold)
TypeError: int() argument must be a string or a number, not 'function'

09/19/2013 13:30:12.270 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 376, in <module>
    items = dict()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 57, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 13:30:12.391 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 375, in <module>
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 57, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 13:30:12.515 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 391, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 57, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 13:37:39.829 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 391, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 60, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 334, in run_command
    inn_system(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 183, in inn_system
    save_game()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 196, in save_game
    room_idx = game_map.building.index(room)
NameError: global name 'room' is not defined

09/19/2013 13:46:09.418 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 391, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 57, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 15:26:28.64 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 397, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 278, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 90, in battle_system
    battle_music()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in battle_music
    sound = pygame.mixer.Sound('battlemusic.mp3')
error: mixer system not initialized

09/19/2013 15:29:05.149 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 397, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 278, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 90, in battle_system
    battle_music()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in battle_music
    sound = pygame.mixer.music('battlemusic.mp3')
TypeError: 'module' object is not callable

09/19/2013 15:31:06.162 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 397, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 278, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 90, in battle_system
    battle_music()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 64, in battle_music
    sound = pygame.mixer.music.load('battlemusic.mp3')
error: mixer system not initialized

09/19/2013 15:32:59.964 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 398, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 279, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 91, in battle_system
    battle_music()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 66, in battle_music
    sound.play
AttributeError: 'NoneType' object has no attribute 'play'

09/19/2013 15:34:15.600 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 398, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 279, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 91, in battle_system
    battle_music()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 66, in battle_music
    sound.play()
AttributeError: 'NoneType' object has no attribute 'play'

09/19/2013 15:44:21.585 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 398, in <module>
    if __name__ =="__main__":
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 59, in main
    describe(current_room)
EOFError: EOF when reading a line

09/19/2013 15:44:21.983 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 400, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 15:44:22.481 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 400, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 15:49:57.884 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 400, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 28, in main
    print str(i) + "\t" + file_name.split(".")[0]
EOFError: EOF when reading a line

09/19/2013 15:49:58.4 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 400, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    last_room = current_room
EOFError: EOF when reading a line

09/19/2013 15:54:39.492 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 402, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 283, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 95, in battle_system
    battle_music()
TypeError: battle_music() takes exactly 1 argument (0 given)

09/19/2013 15:59:39.3 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 405, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 58, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 16:01:31.289 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 405, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 58, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 17:24:25.938 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 405, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 58, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 17:24:26.472 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 405, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 286, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 106, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/19/2013 17:32:58.900 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 405, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 58, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 17:32:59.516 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 405, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 61, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 286, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 106, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/19/2013 18:38:38.684 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 411, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 18:38:38.809 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 411, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 18:42:35.638 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 411, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 21:37:30.322 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 411, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 62, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 21:41:12.871 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 422, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 65, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 303, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 161, in battle_system
    battle_music(69)
TypeError: battle_music() takes exactly 2 arguments (1 given)

09/19/2013 21:43:05.907 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 422, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 65, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 303, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 106, in battle_system
    monster = room.monster[0, room]
TypeError: list indices must be integers, not tuple

09/19/2013 22:32:16.580 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 423, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 63, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 22:32:16.735 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 423, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 63, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/19/2013 23:05:21.231 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 446, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Secret of Text.py", line 63, in main
    command = raw_input(">")
EOFError: EOF when reading a line

